In [1]:
# 1.Import the numpy package under the name np
import numpy as np

In [4]:
#2.Print the numpy version and the configuration 
#For version
print(np.__version__)
#For configaration
np.show_config()

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/sreerag/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/sreerag/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/sreerag/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/sreerag/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/sreerag/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/sreerag/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/sreerag/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/sreerag/anaconda3/include']


In [8]:
#3.Create a null vector of size 10 
x=np.zeros(10)
print(x)
print(x.size)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10


In [9]:
#4.How to find the memory size of any array
print("%d bytes" % (x.size * x.itemsize))
print("Memory size of one array element(in bytes): ",x.itemsize)
  
# memory size of numpy array in bytes
print("Memory size of numpy array(in bytes):",x.size * x.itemsize)

80 bytes
Memory size of one array element(in bytes):  8
Memory size of numpy array(in bytes): 80


In [10]:
#5.How to get the documentation of the numpy add function from the command line?


In [11]:
#6.Create a null vector of size 10 but the fifth value which is 1
y=np.zeros(10)
y[4]=1
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [3]:
#7.Create a vector with values ranging from 10 to 49 
x=np.arange(10,50)
print(x)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
#8.Reverse a vector (first element becomes last) 
x=np.arange(10,50)
y=np.flipud(x)
print(y)
#second method
z=x[::-1]
print(z)
#For multidimensional array use np.fliplr(x)



[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [14]:
#9.Create a 3x3 matrix with values ranging from 0 to 8
x=np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
#10.Find indices of non-zero elements from [1,2,0,0,4,0] 
x=[1,2,0,0,4,0]
k=np.nonzero(x)
print(k)

(array([0, 1, 4]),)


In [17]:
#11.Create a 3x3 identity matrix
x=np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
#12.Create a 3x3x3 array with random values
x=np.random.random((3,3,3))
print(x)
#use seed function to obtain same value of random naumbers in case we are repeating the operation
#eg. np.random.seed(42)

[[[0.12834865 0.430015   0.40083821]
  [0.77516535 0.67912183 0.68364981]
  [0.70457349 0.38749937 0.30083477]]

 [[0.47686953 0.3326441  0.49255641]
  [0.81727279 0.7605479  0.46554196]
  [0.44640459 0.62710933 0.55051627]]

 [[0.89649574 0.36468584 0.94441357]
  [0.29304175 0.02305033 0.31841753]
  [0.78798257 0.55849345 0.19233356]]]


In [31]:
#13.Create a 10x10 array with random values and find the minimum and maximum values
x=np.random.random((10,10))
#np.random.random() returns a value between 0 and 1
y=np.random.randint(1,100,(10,10))
x_min,x_max = x.min(),x.max()
y_min,y_max = y.min(),y.max()
print(x_min,x_max)
print(y_min,y_max)

0.00011265893394130089 0.9894354355461424
3 99


In [34]:
#14.Create a random vector of size 30 and find the mean value
x=np.random.random(30)
mean=x.mean()
print(mean)

0.43278242250524734


In [42]:
#15.Create a 2d array with 1 on the border and 0 inside
x=np.ones((6,6))
x[1:-1,1:-1]=0
print(x)
# using np.pad()
y=np.zeros((6,6))
y=np.pad(y, pad_width=1, mode='constant',
               constant_values=1)
print(y)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [46]:
#16.How to add a border (filled with 0's) around an existing array? 
x=np.random.randint(0,100,(6,6))
print(x)
x=np.pad(x, pad_width=1, mode='constant',
               constant_values=0)
print(x)

[[10  9  0 51 74 18]
 [27 54 24  5 42 59]
 [45 50 54  2 81  8]
 [ 0 58  3 68  3 46]
 [62 48 25 26 77 32]
 [79 13 22 55 40 82]]
[[ 0  0  0  0  0  0  0  0]
 [ 0 10  9  0 51 74 18  0]
 [ 0 27 54 24  5 42 59  0]
 [ 0 45 50 54  2 81  8  0]
 [ 0  0 58  3 68  3 46  0]
 [ 0 62 48 25 26 77 32  0]
 [ 0 79 13 22 55 40 82  0]
 [ 0  0  0  0  0  0  0  0]]


In [47]:
#17.What is the result of the following expression? 
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [54]:
#18.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
x=np.diag(1+np.arange(4),k=-1)
#with k value the diagonal choosen changes
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [70]:
#19.Create a 8x8 matrix and fill it with a checkerboard pattern
x= np.zeros((8,8),dtype=int)
x[1::2,0::2]=1
x[0::2,1::2]=1
#here first input implies the pattern through row-wise and second implies column wise
#first digit in each input implies from which row/column to start
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [77]:
#20.Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
np.random.seed(42)
x=np.random.randint(0,200,(6,7,8))
print(np.unravel_index(99,(6,7,8)))
#For finding index of a specified element list.index(element, start, end)

(1, 5, 3)


In [79]:
#21.Create a checkerboard 8x8 matrix using the tile function
#numpy.tile(arr, repetitions)  
#repetations=(a,b) ,a= row wise repetation, b=column wise repetation
x=[[0,1],[1,0]]
x=np.tile(x,(4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [82]:
#22. Normalize a 5x5 random matrix
x=np.random.randint(0,25,(5,5))
print(x)
x=(x-np.mean (x)) / (np.std (x))
print(x)

[[20  2  0 19 20]
 [22  0  2 17 24]
 [ 9 21  2  7 13]
 [23 17 14 21 22]
 [ 1  9  1 16  7]]
[[ 0.9080425  -1.23132465 -1.46903211  0.78918877  0.9080425 ]
 [ 1.14574996 -1.46903211 -1.23132465  0.55148131  1.38345742]
 [-0.39934853  1.02689623 -1.23132465 -0.63705599  0.07606639]
 [ 1.26460369  0.55148131  0.19492012  1.02689623  1.14574996]
 [-1.35017838 -0.39934853 -1.35017838  0.43262758 -0.63705599]]


In [85]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color=np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [86]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
x=np.random.randint(1,11,(5,3))
y=np.random.randint(1,11,(3,2))
print(np.dot(x,y))

[[118  40]
 [157  51]
 [ 78  23]
 [170  53]
 [128  42]]


In [93]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place
x=np.random.randint(0,21,10)
print(x)
#choosing elements which are between 3 and 8
m=(x>3) & (x<8)
print(m)
#changing the elements of x corresponding to the selected indices
x[m]*=-1
print(x)

[ 4  6  3  5 12 19 14  2  7 19]
[ True  True False  True False False False False  True False]
[-4 -6  3 -5 12 19 14  2 -7 19]


In [94]:
#26. What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


In [97]:
#27. Consider an integer vector Z, which of these expressions are legal? 
z=np.random.randint(1,11,10)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
[[False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [98]:
#28. What are the result of the following expressions? 
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-98-4452e2f85b25>:2: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-98-4452e2f85b25>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [101]:
#29. How to round away from zero a float array ?
#np.random.random() returns a floating value between 0 and 1(including 0)
#random.uniform() = when we want a floating value a between a user deftined range (a,b)
x=np.random.uniform(-20,+20,40)
#copysign(x,y):Return x with the sign of y
print(np.copysign(np.ceil(np.abs(x)),x))

[  8.   5.  18.  18.  15.   6.  13.   8.   3. -15.  13.  13.   6.  13.
   7. -12. -10. -12.  -5. -19.   5.  -7.   7.  -5.   8.  -7. -10.  -1.
   8.  -7.  18. -19.  -4.  19.   2.  -4.   3.   4.  10. -15.]


In [103]:
#30. How to find common values between two arrays? 
#It can be done using np.intersect1d(x,y) for two 1D arrays
x=np.random.randint(0,21,21)
print(x)
y=np.random.randint(0,21,21)
print(y)
z=np.intersect1d(x,y)
print(z)

[ 4  2 10 10 17 14 11  8  9 11 16  5  6 13 12  7  9  8 17  1  4]
[ 4  5 18  7 15 12  0 19 16  6 12  3  3  5 18 11  6  9 18  6  2]
[ 2  4  5  6  7  9 11 12 16]


In [6]:
#31. How to ignore all numpy warnings (not recommended)?
#Suicide mode on
import numpy as np
defaults = np.seterr(all="ignore")
x=np.ones(1) / 0

#Back to sanity
_ = np.seterr(**defaults)

#Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0
    
#make use of the Warnings module to ignore all warnings with filterwarnings
warnings.filterwarnings('ignore')
import warnings
#if we want to suppress uniquely your particular error, you could specify it with:
with warnings.catch_warnings():
    warnings.filterwarnings('ignore', r'All-NaN (slice|axis) encountered')


In [7]:
#32.Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [8]:
#33. How to get the dates of yesterday, today and tomorrow?
yesterday=np.datetime64('today') - np.timedelta64(1)
today=np.datetime64('today')
tomorrow=np.datetime64('today') + np.timedelta64(1)

In [11]:
#34. How to get all the dates corresponding to the month of July 2016? 
#Syntax: numpy.arrange([start, ] stop, [step, ] dtype=None)
#Parameters: start : Start of interval   stop : End of interval
x=np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [21]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)?
#Syntax: numpy.ones(shape, dtype = None, order = 'C') 
A=np.ones((3,3))*1
print(A)
B=np.ones((3,3))*2
print(B)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


array([[-1.5, -1.5, -1.5],
       [-1.5, -1.5, -1.5],
       [-1.5, -1.5, -1.5]])

In [24]:
#36. Extract the integer part of a random array of positive numbers using 4 different methods
x=np.random.uniform(0,20,25)
print(x)
#np.trunc() returns closest integer(less than or equal to) of the elements of the input array
y=np.trunc(x)
print(y)
# x.astype(Data type) coverts values in x to inputted data type
y=x.astype(int)
print(y)
#we can also use np.floor()
#int rounds towards 0, while floor rounds towards negative infinity
y=np.floor(x)
print(y)
print(x%1)
print(x-x%1)
print(x//1)




[18.62653634  3.80756043 14.14719123 13.08869217  3.49192561  7.76444134
  7.63770287 10.81094859  6.75146316 12.48233666 16.03989009  0.06356032
 14.05938022  2.27666378  3.07536832 18.63226361  3.91645744  4.47301887
  9.74262049 17.9836997  11.19511311 15.94856081 19.6851837   3.74475806
 12.88963251]
[18.  3. 14. 13.  3.  7.  7. 10.  6. 12. 16.  0. 14.  2.  3. 18.  3.  4.
  9. 17. 11. 15. 19.  3. 12.]
[18  3 14 13  3  7  7 10  6 12 16  0 14  2  3 18  3  4  9 17 11 15 19  3
 12]
[18.  3. 14. 13.  3.  7.  7. 10.  6. 12. 16.  0. 14.  2.  3. 18.  3.  4.
  9. 17. 11. 15. 19.  3. 12.]
[0.62653634 0.80756043 0.14719123 0.08869217 0.49192561 0.76444134
 0.63770287 0.81094859 0.75146316 0.48233666 0.03989009 0.06356032
 0.05938022 0.27666378 0.07536832 0.63226361 0.91645744 0.47301887
 0.74262049 0.9836997  0.19511311 0.94856081 0.6851837  0.74475806
 0.88963251]
[18.  3. 14. 13.  3.  7.  7. 10.  6. 12. 16.  0. 14.  2.  3. 18.  3.  4.
  9. 17. 11. 15. 19.  3. 12.]
[18.  3. 14. 13.  3.  7.  

In [12]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4
#using np.arange()
import numpy as np
x=np.arange(5)
print(x)
y=np.append(x,x,axis=0)
print(y)
z=[]
for i in range(5):
    z.append(x)
print(z)
a=np.array(z)
print(a)

#another method
a=np.zeros((5,5))
a+=np.arange(5)
print(a)

#using np.tile
#numpy.tile(arr, repetitions)
#repetitions : No. of repetitions of arr along each axis. 
y=np.tile(x,(5,1))
print(y)

[0 1 2 3 4]
[0 1 2 3 4 0 1 2 3 4]
[array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4])]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [20]:
#38. Consider a generator function that generates 10 integers and use it to build an array
def generate():
    for i in range(10):
        yield i
print(generate())
y=[]
for value in generate():
    y.append(value)
print(y)

#using np.fromiter() (function create a new one-dimensional array from an iterable object)
#numpy.fromiter(iterable, dtype, count = -1)
y=np.fromiter(generate(),float)
print(y)

<generator object generate at 0x7fc638d53f90>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [61]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
#using np.linspace
#syntax numpy.linspace(start,stop,num = 50,endpoint = True,retstep = False,dtype = None)
x=np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [27]:
#40. Create a random vector of size 10 and sort it 
x=np.random.uniform(0,5,10)
print(x)
y=np.sort(x)
print(y)

[2.13277063 2.32625496 2.42233295 1.58095968 4.48027912 3.00337251
 4.89903781 0.06261659 1.65715062 1.91407338]
[0.06261659 1.58095968 1.65715062 1.91407338 2.13277063 2.32625496
 2.42233295 3.00337251 4.48027912 4.89903781]


In [28]:
#41. How to sum a small array faster than np.sum? 
#it can be done using np.add.reduce()
x=np.arange(10)
np.add.reduce(x)

45

In [44]:
#42. Consider two random array A and B, check if they are equal
x=np.random.randint(0,10,(3,3))
y=np.random.randint(0,10,(3,3))
print(x)
print(y)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
#Syntax : numpy.allclose(arr1, arr2, rtol, atol, equal_nan=False)
#Parameters :rtol : [float] The relative tolerance parameter.
#atol : [float] The absolute tolerance parameter.
#equal_nan : [bool] Whether to compare NaN’s as equal. If True, NaN’s in arr1 will be 
#considered equal to NaN’s in arr2 in the output array.
equal=np.allclose(x,y)
print(equal)
#numpy.array_equal(arr1, arr2) 
#True, if both arrays have same shape and value; otherwise False
equal=np.array_equal(x,y)
print(equal)

[[8 8 9]
 [7 9 0]
 [7 8 9]]
[[1 9 9]
 [7 8 4]
 [9 7 8]]
False
False


In [47]:
#43. Make an array immutable (read-only)
x=np.zeros((3,3))
print(x)
x.flags.writeable = False
x[2][2]=1


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


ValueError: assignment destination is read-only

In [53]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
Z=np.random.random((10,2))
print(Z)
#assigning each columns to x and y
X,Y = Z[:,0], Z[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)
np.vstack([X,Y])

[[0.42728636 0.38491368]
 [0.10174865 0.23612397]
 [0.90119539 0.63594294]
 [0.67252113 0.40884693]
 [0.95902734 0.53281884]
 [0.08376274 0.6117958 ]
 [0.11917459 0.99391299]
 [0.84910503 0.7014887 ]
 [0.51772658 0.34847222]
 [0.10053528 0.57431073]]
[0.57509319 0.25711343 1.1029853  0.78704541 1.09710043 0.61750327
 1.00103228 1.10139264 0.62407829 0.58304387]
[0.73327517 1.16392885 0.61451853 0.54623125 0.50711912 1.43472941
 1.45146159 0.69048433 0.59243055 1.39749845]


array([[0.42728636, 0.10174865, 0.90119539, 0.67252113, 0.95902734,
        0.08376274, 0.11917459, 0.84910503, 0.51772658, 0.10053528],
       [0.38491368, 0.23612397, 0.63594294, 0.40884693, 0.53281884,
        0.6117958 , 0.99391299, 0.7014887 , 0.34847222, 0.57431073]])

In [58]:
#45. Create random vector of size 10 and replace the maximum value by 0 
#using argmax()
#syntax : numpy.argmax(array, axis = None, out = None)
x=np.random.uniform(0,5,10)
indices=x.argmax()
print(x)
print(indices)
x[indices]=0
print(x)

[2.21588199 4.60959949 4.12578047 4.07260745 2.14726183 1.03784912
 0.79592032 1.79101157 2.18253621 3.95180349]
1
[2.21588199 0.         4.12578047 4.07260745 2.14726183 1.03784912
 0.79592032 1.79101157 2.18253621 3.95180349]


In [63]:
#46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area 
Z = np.zeros((5,5), [('x',float),('y',float)])
print(Z)
#syntax numpy.linspace(start,stop,num = 50,endpoint = True,retstep = False,dtype = None)
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)
print(Z['x'])
print(Z['y'])
#another way
x = np.linspace(0, 1, 5)
  
# numpy.linspace creates an array of
# 3 linearly placed elements between
# 0 and 1, both inclusive 
y = np.linspace(0, 1, 5)
  
# The meshgrid function returns
# two 2-dimensional arrays 
x_1, y_1 = np.meshgrid(x, y)
  
print("x_1 = ")
print(x_1)
print("y_1 = ")
print(y_1)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]
[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]
[[0.   0.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25 0.25]
 [0.5  0.5  0.5  0.5  0.5 ]
 [0.75 0.75 0.75 0.75 0.75]
 [1.   1.   1.   1.   1.  ]]
x_1 = 
[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  

In [67]:
#47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
X = np.arange(10)
print(x)
Y = X + 0.5
xi_yj=np.subtract.outer(X, Y)
print(xi_yj)
C = 1.0 / np.subtract.outer(X, Y)

print(C)

[0.   0.25 0.5  0.75 1.  ]
[[-0.5 -1.5 -2.5 -3.5 -4.5 -5.5 -6.5 -7.5 -8.5 -9.5]
 [ 0.5 -0.5 -1.5 -2.5 -3.5 -4.5 -5.5 -6.5 -7.5 -8.5]
 [ 1.5  0.5 -0.5 -1.5 -2.5 -3.5 -4.5 -5.5 -6.5 -7.5]
 [ 2.5  1.5  0.5 -0.5 -1.5 -2.5 -3.5 -4.5 -5.5 -6.5]
 [ 3.5  2.5  1.5  0.5 -0.5 -1.5 -2.5 -3.5 -4.5 -5.5]
 [ 4.5  3.5  2.5  1.5  0.5 -0.5 -1.5 -2.5 -3.5 -4.5]
 [ 5.5  4.5  3.5  2.5  1.5  0.5 -0.5 -1.5 -2.5 -3.5]
 [ 6.5  5.5  4.5  3.5  2.5  1.5  0.5 -0.5 -1.5 -2.5]
 [ 7.5  6.5  5.5  4.5  3.5  2.5  1.5  0.5 -0.5 -1.5]
 [ 8.5  7.5  6.5  5.5  4.5  3.5  2.5  1.5  0.5 -0.5]]
[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333 -0.11764706 -0.10526316]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615 -0.13333333 -0.11764706]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818 -0.15384615 -0.13333333]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4


In [73]:
#48. Print the minimum and maximum representable value for each numpy scalar type
#numpy scalar types are int(8,32 and 64) and float(32 and 64)
#for int
print("for int8, int32 and int64 are respectively ")
for i in [np.int8, np.int32, np.int64]:
   print(np.iinfo(i).min)
   print(np.iinfo(i).max)
#for float
print("for float32 and float64 are respectively ")
for i in [np.float32, np.float64]:
   print(np.finfo(i).min)
   print(np.finfo(i).max)
   print(np.finfo(i).eps)

for int8, int32 and int64 are respectively 
-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
for float32 and float64 are respectively 
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [6]:
#49. How to print all the values of an array?
import numpy as np
np.set_printoptions(threshold=np.inf)
#it implies that threshold is infinity
x=np.random.uniform(0,15,(3,3))
print(x)
#another way
import sys
np.set_printoptions(threshold=sys.maxsize)
x=np.random.uniform(0,15,(15,15))
print(x)

[[ 0.15389315  6.0926917  11.9598979 ]
 [11.30912056  5.34344187 13.34813505]
 [11.03580915  0.49928915 11.95614063]]
[[10.10795691  9.60964262 13.50398454  1.28553447  1.0702664   2.99165692
   7.06665688 12.00782354  8.45828172 10.59433729  5.94036561  5.10018169
  13.66148759  9.21936876  8.58627367]
 [ 1.59946725 11.49537708 13.26020098 12.46383394  8.30443363  7.24538864
   7.16773354 11.55593948  2.953946    4.22360645  9.97094373 13.10520985
   0.60980432  1.28760572 10.35379115]
 [11.39045918 13.27771173  1.40139225 14.26077678  2.99158151  9.93037941
   9.84446123  3.24490981 13.74362895 11.31999847  4.48034185  8.7166493
   4.18442671  9.05730074  2.678321  ]
 [ 2.70842464  5.22396305  2.18918214 14.78242936  0.03744078  2.51965569
   1.13200438 14.70590505 14.90135291  9.31057291  5.6628029  14.22374462
  11.87023208  9.34436947 11.58945249]
 [ 9.48807276  9.03681752 10.99389443  5.21928456  7.50744465  5.32724915
   4.92688071  4.04966651  4.52860664  9.60446267  2.39191569

In [52]:
#50. How to find the closest value (to a given scalar) in a vector? 
#numpy.argmin(array, axis = None, out = None)

V=np.random.uniform(0,100,150)
print(V)
#defining scalar
S= np.random.uniform(0,100)
print(S)
index = (np.abs(V-S)).argmin()
print(index)
closest_value=V[index]
print(closest_value)
# Second method
close_value=V.flat[np.abs(V-S).argmin()]
print(close_value)

[19.4475719  81.15097265 82.95851956 11.73097175 34.20155061 96.06156567
 84.85016267 33.35473411 26.25813814  5.84825073 88.14147895  5.82453678
 15.86836547 23.10793746 49.15510846 26.71205354  0.64210238 48.030689
 46.29828169 99.95491514 96.87495118 33.02532999 19.48251227 21.75304876
 58.10306267 62.59279811 77.75571752 35.6401446  95.5129866  29.57524063
 12.01455405 64.12873924 74.18571086 68.34998535 82.60231143 41.30047408
 29.96495954 42.83866361  9.16252495 54.23882446 24.02810168 48.74153321
 38.95885337 11.89959531 34.84076583 40.3164064   9.16514712  2.11029271
 32.55250901 10.00554366 98.9696143   9.50515164 69.53753002 28.80854124
  8.06841376 38.74555887 88.49373391  1.37608767  1.88230334 11.28663946
 42.31273451 72.76988837 87.30171542 66.17959097 71.72664574 54.47031693
 56.15216893 81.42312609 89.4795117  66.39380586 45.67985997 62.23859582
 72.0773598  17.72694351 20.7997185   6.81880794 69.15283198 27.07363136
 59.88428588 91.86419585 96.51843716 50.4842695  51.6

In [25]:
#51. Create a structured array representing a position (x,y) and a color (r,g,b)
x = np.zeros(20, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-25-161545694afb>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.zeros(20, [ ('position', [ ('x', float, 1),


In [28]:
#52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances
#using scipy
import scipy
import scipy.spatial

x=np.random.random((10,2))
Distance=scipy.spatial.distance.cdist(Z,Z)
print(Distance)

[[0.         0.89440716 0.52076591 1.16588001 0.64741036 0.91600936
  0.81137866 0.55561239 0.53393176 0.80496007]
 [0.89440716 0.         0.37657809 0.37675577 0.33634817 0.05637259
  0.83590293 0.39501801 0.44345639 0.09814419]
 [0.52076591 0.37657809 0.         0.66144482 0.18482874 0.4047464
  0.66243884 0.19465291 0.23296825 0.28452489]
 [1.16588001 0.37675577 0.66144482 0.         0.51991725 0.40854892
  0.80675161 0.74871175 0.80012476 0.41361611]
 [0.64741036 0.33634817 0.18482874 0.51991725 0.         0.38422871
  0.5355938  0.3607941  0.40670016 0.24113551]
 [0.91600936 0.05637259 0.4047464  0.40854892 0.38422871 0.
  0.89085351 0.39631446 0.4417677  0.14309342]
 [0.81137866 0.83590293 0.66243884 0.80675161 0.5355938  0.89085351
  0.         0.85664739 0.89036177 0.75531082]
 [0.55561239 0.39501801 0.19465291 0.74871175 0.3607941  0.39631446
  0.85664739 0.         0.05200983 0.33528295]
 [0.53393176 0.44345639 0.23296825 0.80012476 0.40670016 0.4417677
  0.89036177 0.0520098

In [33]:
#53. How to convert a float (32 bits) array into an integer (32 bits) in place?
x=np.random.random((10,2))
print(x.dtype)
y=x.astype(np.float32)
print(y.dtype)
z=y.astype(np.int32)
print(z.dtype)

float64
float32
int32


In [38]:
#How to read the following file?
from io import StringIO
#The StringIO module is an in-memory file-like object. This object can be
#used as input or output to the most function that would expect a standard
#file object as input or output to the most function that would expect a standard file object
file= StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                ,  , 9,10,11''')
x = np.genfromtxt(file, delimiter=",", dtype=np.int)
print(x)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [41]:
#What is the equivalent of enumerate for numpy arrays?
x = np.random.uniform(0,10,15).reshape(5,3)
for index, value in np.ndenumerate(x):
    print(index, value)
#np.ndindex(x.shape) will return index looking into shape of the array
print(np.ndindex(x.shape))
for index in np.ndindex(x.shape):
    print(index, x[index])

(0, 0) 4.277778365071367
(0, 1) 4.605341798158876
(0, 2) 2.94403988429764
(1, 0) 7.5371497590824434
(1, 1) 0.13616438212206927
(1, 2) 1.5808073420595459
(2, 0) 9.441336034060539
(2, 1) 7.170658760660606
(2, 2) 1.3207340492223263
(3, 0) 4.545936282410251
(3, 1) 2.6599832309295834
(3, 2) 7.682802806336403
(4, 0) 8.953377814204869
(4, 1) 0.48907617171222273
(4, 2) 6.355247608529497
(0, 0) 4.277778365071367
(0, 1) 4.605341798158876
(0, 2) 2.94403988429764
(1, 0) 7.5371497590824434
(1, 1) 0.13616438212206927
(1, 2) 1.5808073420595459
(2, 0) 9.441336034060539
(2, 1) 7.170658760660606
(2, 2) 1.3207340492223263
(3, 0) 4.545936282410251
(3, 1) 2.6599832309295834
(3, 2) 7.682802806336403
(4, 0) 8.953377814204869
(4, 1) 0.48907617171222273
(4, 2) 6.355247608529497


In [42]:
#56. Generate a generic 2D Gaussian-like array 
x=np.linspace(-3,3,18)
y=np.linspace(-3,3,18)
X, Y = np.meshgrid(x,y)
D=np.sqrt(X*X+Y*Y)
sigma,mu = 1.0, 0.0
G=np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[1.23409804e-04 3.34303864e-04 7.99528892e-04 1.68821580e-03
  3.14718878e-03 5.17986762e-03 7.52688985e-03 9.65636101e-03
  1.09373588e-02 1.09373588e-02 9.65636101e-03 7.52688985e-03
  5.17986762e-03 3.14718878e-03 1.68821580e-03 7.99528892e-04
  3.34303864e-04 1.23409804e-04]
 [3.34303864e-04 9.05593149e-04 2.16583763e-03 4.57319473e-03
  8.52539534e-03 1.40317033e-02 2.03895337e-02 2.61580416e-02
  2.96281267e-02 2.96281267e-02 2.61580416e-02 2.03895337e-02
  1.40317033e-02 8.52539534e-03 4.57319473e-03 2.16583763e-03
  9.05593149e-04 3.34303864e-04]
 [7.99528892e-04 2.16583763e-03 5.17986762e-03 1.09373588e-02
  2.03895337e-02 3.35585479e-02 4.87640828e-02 6.25601805e-02
  7.08593166e-02 7.08593166e-02 6.25601805e-02 4.87640828e-02
  3.35585479e-02 2.03895337e-02 1.09373588e-02 5.17986762e-03
  2.16583763e-03 7.99528892e-04]
 [1.68821580e-03 4.57319473e-03 1.09373588e-02 2.30943775e-02
  4.30527694e-02 7.08593166e-02 1.02966004e-01 1.32096647e-01
  1.49620382e-01 1.49620382e-01 1

In [44]:
#57. How to randomly place p elements in a 2D array?
#using numpy.random.choice()
#Syntax: numpy.random.choice( a , size = None, replace = True, p = None)
m = 10
n=15
p = 12
x = np.zeros((m,n))
#Syntax: numpy.put(array, indices, p_array, mode = 'raise')
np.put(x, np.random.choice(range(m*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


In [46]:
#58. Subtract the mean of each row of a matrix 
X = np.random.randint(0,15,(3,3))
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
#keepdims = true implies array has restored it's collapsed dimension
print(Y)

[[-6.          6.          0.        ]
 [-0.66666667 -3.66666667  4.33333333]
 [-1.66666667 -3.66666667  5.33333333]]


In [49]:
#59. How to sort an array by the nth column?
x = np.random.randint(0,15,(6,6))
print(x)
#sorting about the third column
y=x[x[:,3].argsort()]
print(y)

[[ 2  2  3 12  5  3]
 [10  9  6  8 12 13]
 [10  4 10 10 11  4]
 [ 4  9  8  2  7  2]
 [10  4  6 11  5  2]
 [ 0  7  6  7  1 10]]
[[ 4  9  8  2  7  2]
 [ 0  7  6  7  1 10]
 [ 2  2  3 12  5  3]
 [10  4  6 11  5  2]
 [10  4 10 10 11  4]
 [10  9  6  8 12 13]]


In [51]:
#60. How to tell if a given 2D array has null columns?
X = np.random.randint(0,15,(3,3))
print(X)
print((~X.any(axis=0)).any())

[[14  5  4]
 [ 5  8  1]
 [12 14 10]]
False


In [56]:
#61. Find the nearest value from a given value in an array
X = np.random.uniform(0,15,(3,3))
v=6
close_value=X.flat[np.abs(X-v).argmin()]
print(close_value)

4.562741215560503


In [59]:
#62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?
X = np.random.uniform(0,15,(3,1))
Y = np.random.uniform(0,15,(1,3))
#numpy.nditer() Efficient multi-dimensional iterator object to iterate over arrays.
it = np.nditer([X,Y,None])
print(it)
for x,y,z in it: z[...] = x + y
print(it.operands[2])
z=[]
for x,y,z in it: z.append = x + y
print(it.operands[2])

[[12.47943929 21.50752813 18.21123613]
 [ 5.67440967 14.70249851 11.40620652]
 [17.17530659 26.20339544 22.90710344]]
[[12.47943929 21.50752813 18.21123613]
 [ 5.67440967 14.70249851 11.40620652]
 [17.17530659 26.20339544 22.90710344]]


In [67]:
#63. Create an array class that has a name attribute 
class Array_class(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = Array_class(np.arange(10), "range_10")
print (Z)
print(Z.name)

[0 1 2 3 4 5 6 7 8 9]
range_10


In [78]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
x = np.random.randint(0,10,10)
indexing_vector = np.array([1,2,5,7,9])
print(x)
print(indexing_vector)
np.add.at(x, indexing_vector, 1)
print(x)


[2 1 4 7 2 2 0 8 6 5]
[1 2 5 7 9]
[2 2 5 7 2 3 0 9 6 6]


In [80]:
#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?
X = np.random.randint(0,10,10)
print(X)
indexing_vector = np.random.randint(0,10,10)
print(indexing_vector)
F = np.bincount(indexing_vector,X)
print(F)

[3 0 8 9 2 5 5 6 1 9]
[3 6 0 2 1 3 8 2 0 5]
[ 9.  2. 15.  8.  0.  9.  0.  0.  5.]


In [81]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors


In [84]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once?

x=np.random.randint(0,10,(3,3,3,3))
sum=x.sum(axis=(-2,-1))
print(sum)

[[53 38 40]
 [45 41 44]
 [32 52 44]]


In [85]:
#68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?


In [86]:
#69. How to get the diagonal of a dot product?
X = np.random.uniform(0,15,(6,6))
Y = np.random.uniform(0,15,(6,6))
diag=np.diag(np.dot(X,Y))
print(diag)

[342.84953757 635.4379599  290.45667439 447.63483534 396.01088607
 278.09584429]


In [115]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?
x=[1,2,3,4,5]
index=np.array([1,2,3,4])
for i in range(3):
    x=np.insert(x, [4], 0, axis=0)
for i in range(3):
    x=np.insert(x, [3], 0, axis=0)  
for i in range(3):
    x=np.insert(x, [2], 0, axis=0)
for i in range(3):
    x=np.insert(x, [1], 0, axis=0)    
print(x)


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


In [116]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)
x = np.random.randint(0,10,(5,5,3))
B = 2*np.random.randint(0,10.(5,5))
print(A * B[:,:,None])

<>:3: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<>:3: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<ipython-input-116-709973d0dcff>:3: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
  B = 2*np.random.randint(0,10.(5,5))


TypeError: 'float' object is not callable

In [12]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
import numpy as np
z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
type(z[1])
x=np.arange(z[1],z[1+4])
print(x)
y=[]
for i in range(14):
           k=np.arange(z[i],z[i]+4)
           y.append(k)
print(np.array(y))

[2 3 4 5]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]
 [12 13 14 15]
 [13 14 15 16]
 [14 15 16 17]]


In [18]:
#82. Compute a matrix rank
x = np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(np.linalg.matrix_rank(x))

2


In [21]:
#83. How to find the most frequent value in an array?
x = np.random.randint(0,15,100)
print(x)
freq_value=np.bincount(x).argmax()
print(freq_value)

[ 0  3 11 12  5 14 13  9  9 13  4 13 11  1  6  8  1  5 12  1  9  0  3 14
  2  5  1  9 11  3  1 14  9  7  3  4 11 14  0  7  7  3 14  9  4  9  4 12
  4  7 10  2  3 12  2 13 12  4  9  2  9  4  6  6 11  3  3  4 11  6  0 12
  3  0  1  7  8 10  1 14  7  9 10  3  5  2  7  2  0 10 10  9 11  4  6  1
  4  2  3 10]
3


In [34]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
x= np.random.uniform(0,10,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
blocks = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(blocks)

[[[[0 2 1]
   [3 4 4]
   [1 3 4]]

  [[2 1 2]
   [4 4 0]
   [3 4 4]]

  [[1 2 2]
   [4 0 0]
   [4 4 0]]

  [[2 2 0]
   [0 0 2]
   [4 0 4]]

  [[2 0 1]
   [0 2 1]
   [0 4 4]]

  [[0 1 2]
   [2 1 2]
   [4 4 2]]

  [[1 2 0]
   [1 2 1]
   [4 2 0]]

  [[2 0 2]
   [2 1 1]
   [2 0 1]]]


 [[[3 4 4]
   [1 3 4]
   [1 4 4]]

  [[4 4 0]
   [3 4 4]
   [4 4 1]]

  [[4 0 0]
   [4 4 0]
   [4 1 3]]

  [[0 0 2]
   [4 0 4]
   [1 3 2]]

  [[0 2 1]
   [0 4 4]
   [3 2 0]]

  [[2 1 2]
   [4 4 2]
   [2 0 4]]

  [[1 2 1]
   [4 2 0]
   [0 4 1]]

  [[2 1 1]
   [2 0 1]
   [4 1 3]]]


 [[[1 3 4]
   [1 4 4]
   [3 4 1]]

  [[3 4 4]
   [4 4 1]
   [4 1 4]]

  [[4 4 0]
   [4 1 3]
   [1 4 2]]

  [[4 0 4]
   [1 3 2]
   [4 2 3]]

  [[0 4 4]
   [3 2 0]
   [2 3 0]]

  [[4 4 2]
   [2 0 4]
   [3 0 3]]

  [[4 2 0]
   [0 4 1]
   [0 3 1]]

  [[2 0 1]
   [4 1 3]
   [3 1 3]]]


 [[[1 4 4]
   [3 4 1]
   [2 4 2]]

  [[4 4 1]
   [4 1 4]
   [4 2 2]]

  [[4 1 3]
   [1 4 2]
   [2 2 0]]

  [[1 3 2]
   [4 2 3]
   [2 0 2]]

  [[3 2 0]
   

In [32]:
#85. Create a 2D array subclass such that Z[i,j] == Z[j,i] 
#definig class for symmmetric 2D array
class Symetric2D(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric2D, self).__setitem__((i,j), value)
        super(Symetric2D, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric2D)

Sym_array = symetric(np.random.randint(0,10,(5,5)))
print(Sym_array)



[[ 4  6  4  5  7]
 [ 6  6  6 13  8]
 [ 4  6  6 10  8]
 [ 5 13 10  9  6]
 [ 7  8  8  6  4]]


In [35]:
#86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))
p, n = 10, 20
#creating set of p matrices wich shape (n,n)
A = np.ones((p,n,n))
#creating set of p vectors with shape (n,1)
print(A)
V = np.ones((p,n,1))
print(V)
S = np.tensordot(A, V, axes=[[0, 2], [0, 1]])
print(S)

[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
[[[1.]
  [

In [41]:
#87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
x = np.ones((16,16))
k = 4
Sum = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], k), axis=0),
                                       np.arange(0, x.shape[1], k), axis=1)
print(Sum)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [39]:
#89. How to get the n largest values of an array
x = np.random.randint(0,500,1000)
n = 10
print (x[np.argsort(x)[-n:]])

[497 497 497 498 498 498 499 499 499 499]
